app = "seetheseabot"
primary_region = "ams"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
[http_service] auto_start_machines = true auto_stop_machines = false force_https = true internal_port = 8080 min_machines_running = 1
