# fly.toml app configuration file generated for seetheseabot on 2026-08-14T03:17:28Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seetheseabot'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
